train_df_path: '../../../input/modified-train-whale-and-dolphin-dataset/modified_train.csv'
train_dataset_path: '../../../input/happy-whale-and-dolphin/train_images'
test_df_path: '../../../input/happy-whale-and-dolphin/sample_submission.csv'
test_dataset_path: '../../../input/happy-whale-and-dolphin/test_images'
save_folder: 'results/vgg16_faiss_clusters_100'
happy_model_weights: ''
train_embeddings_path: ''
test_embeddings_path: ''
train_labels_path: ''

training:
  lr: 1e-4
  adam_weight_decay: 1e-6
  n_epochs: 5
  batch_size: 4
  num_workers: 1
  random_seed: 42
  embedding_size: 128
  threshold_distance: 5
  faiss_clusters: 100

logs:
  use_clearml: True
  vis_freq: 50
  project_name: 'whale_and_dolphin'
  task_name: 'vgg16_faiss_clusters_100'
